
package provemaxgrupo25.Vistas;

import java.time.LocalDate;
import java.time.ZoneId;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import provemaxgrupo25.Data.DetalleCompraData;
import provemaxgrupo25.Entidades.*;


public class ProductoPorFecha extends javax.swing.JInternalFrame {

    private DefaultTableModel model;
     private DetalleCompraData dcd;
     private List<DetalleCompra> listaDC;
     
    public ProductoPorFecha() {
        initComponents();
        model= new DefaultTableModel();
        dcd= new DetalleCompraData();
        LocalDate fecha = LocalDate.now();
        listaDC= dcd.listarProductoPorFecha(fecha);
        jdchFecha.addPropertyChangeListener(evt -> jdchFechaPropertyChange(evt));
        editartabla();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdchFecha = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtProdXFecha = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Producto por Fecha"));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setMinimumSize(new java.awt.Dimension(550, 400));
        setPreferredSize(new java.awt.Dimension(550, 400));

        jdchFecha.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jdchFechaInputMethodTextChanged(evt);
            }
        });
        jdchFecha.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jdchFechaPropertyChange(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Seleccione una Fecha:");

        jtProdXFecha.setBackground(new java.awt.Color(102, 255, 255));
        jtProdXFecha.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(jtProdXFecha);

        jSeparator1.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jdchFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jdchFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jdchFechaInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jdchFechaInputMethodTextChanged
       System.out.print("error");
    }//GEN-LAST:event_jdchFechaInputMethodTextChanged

    private void jdchFechaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jdchFechaPropertyChange
       try{
        
          if ("date".equals(evt.getPropertyName())) { 
        // Obtener la fecha seleccionada del jdchFecha
        LocalDate fechaSeleccionada = jdchFecha.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
  
        cargarProducto(fechaSeleccionada);
          } 
            
       }catch(NullPointerException e){
           JOptionPane.showMessageDialog(null,"Error al cargar");
           } 
       
    }//GEN-LAST:event_jdchFechaPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private com.toedter.calendar.JDateChooser jdchFecha;
    private javax.swing.JTable jtProdXFecha;
    // End of variables declaration//GEN-END:variables

private void editartabla(){
    
    model.addColumn("Nombre Producto");
    model.addColumn("Cantidad");
    model.addColumn("Precio Costo");
    
    jtProdXFecha.setModel(model); 
}

private void cargarProducto(LocalDate fecha) {
    listaDC= dcd.listarProductoPorFecha(fecha);
    
    model.setRowCount(0); // Limpia la tabla antes de cargar nuevos datos
    if (listaDC.isEmpty()){
    
    JOptionPane.showMessageDialog(this, "Lista Vacia" );
    }else {
        for (DetalleCompra item : listaDC) {
            model.addRow(new Object[]{
            item.getProducto().getNombreProd(),
            item.getCantidad(),
            item.getPrecioCosto()
           
            
        });
    }
}
}
}
