/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package provemaxgrupo25.Vistas;

import provemaxgrupo25.Data.ProductoData;
import provemaxgrupo25.Data.ProveedorData;
import provemaxgrupo25.Entidades.Producto;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import provemaxgrupo25.Entidades.Proveedor;

/**
 *
 * @author HP
 */
public class ProvedorPorProducto extends javax.swing.JInternalFrame {

    ProveedorData provdata = new ProveedorData();
    ProductoData prodata = new ProductoData();
    private DefaultTableModel modelo= new DefaultTableModel();
    List<Producto> listam = prodata.ListarProducto();
    /**
     * Creates new form provedorPorProducto
     */
    public ProvedorPorProducto() {
        initComponents();
        armarCabecera();
        mostarProducto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCListaProd = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTProveedXProd = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Proveedor por Producto"));
        setClosable(true);
        setIconifiable(true);

        jCListaProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCListaProdActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Seleccione un Producto:");

        jSeparator1.setBackground(new java.awt.Color(153, 153, 255));

        jTProveedXProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTProveedXProd);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(42, 42, 42)
                        .addComponent(jCListaProd, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCListaProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCListaProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCListaProdActionPerformed
        borrarFilas();
         if(jCListaProd.getSelectedItem() == "-"){
             return;
         }else{
             
         int opcion = jCListaProd.getSelectedIndex();
            //jCListaProd.getSelectedItem().toString());
           //listam.get(opcion + 1);
         
             cargarProveedorXProduc(jCListaProd.getSelectedItem().toString());
             
         }
    }//GEN-LAST:event_jCListaProdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCListaProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTProveedXProd;
    // End of variables declaration//GEN-END:variables

    
    private void armarCabecera(){
        modelo.addColumn("ID");
        modelo.addColumn("Razon Social");
        modelo.addColumn("CUIT");
        modelo.addColumn("Telefono");
        jTProveedXProd.setModel(modelo);
        
    }
    
    private void borrarFilas(){
            int filas = modelo.getRowCount() - 1;
        
            for (int f = filas; f >= 0; f--) {
                modelo.removeRow(f);
        }
    }
    
    private void mostarProducto() {
        
        for (int i=0;i<listam.size(); i++){
            jCListaProd.addItem(listam.get(i).getNombreProd());
    }
    }
    
    private void cargarProveedorXProduc (String nombreprod){
       
        List<Proveedor> listaP = provdata.obtenerProveedorPorProducto(nombreprod);
        modelo = (DefaultTableModel)jTProveedXProd.getModel();
        
        for (Proveedor prod : listaP) {
            if(nombreprod == jCListaProd.getSelectedItem()){

                    modelo.addRow(new Object[]{prod.getIdProveedor(), prod.getRazonSocial(),prod.getCuit(), prod.getTelefono()});
                }
        }
    }

}
